# Alertmanager configuration for Eternia
global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for all alerts.
  # The default receiver is the one that handles alerts that do not match any of the nested routes.
  receiver: 'ops-team'

  # The child route trees.
  routes:
    # Route for critical alerts
    - match:
        severity: critical
      receiver: 'ops-team-pager'
      continue: true
      
    # Route for warning alerts
    - match:
        severity: warning
      receiver: 'ops-team'
      continue: true

  # How long to wait before sending a notification again if it has already been sent successfully for an alert.
  repeat_interval: 4h

# Inhibition rules allow to mute a set of alerts given that another alert is firing.
inhibit_rules:
  # Inhibit warnings if a critical alert is firing for the same instance
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['instance']

# Receivers define notification integrations.
receivers:
  - name: 'ops-team'
    email_configs:
      - to: 'ops-team@example.com'
        send_resolved: true
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

  - name: 'ops-team-pager'
    email_configs:
      - to: 'ops-team-pager@example.com'
        send_resolved: true
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        send_resolved: true
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#critical-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'