# Prometheus alerting rules for Eternia

groups:
  - name: eternia_alerts
    rules:
      # Alert for high CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage (instance {{ $labels.instance }})"
          description: "CPU usage is above 80% for 5 minutes\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Alert for high memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage (instance {{ $labels.instance }})"
          description: "Memory usage is above 80% for 5 minutes\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Alert for disk space running out
      - alert: DiskSpaceRunningOut
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk space running out (instance {{ $labels.instance }})"
          description: "Disk space is below 10% for 5 minutes\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Alert for service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service down (instance {{ $labels.instance }})"
          description: "Service {{ $labels.job }} is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Alert for high HTTP error rate
      - alert: HighHTTPErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP error rate (instance {{ $labels.instance }})"
          description: "HTTP error rate is above 5% for 5 minutes\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Alert for slow HTTP response time
      - alert: SlowHTTPResponseTime
        expr: http_request_duration_seconds{quantile="0.9"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow HTTP response time (instance {{ $labels.instance }})"
          description: "HTTP response time is above 1 second for 5 minutes\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"