[meta]
name        = "Reciprocity"
version     = 1
enabled     = true
description = "Entities that receive help feel gratitude and repay positive actions."

[trigger]
on_event    = ["companion_spawn", "modifier_applied"]

# Simple boolean filter language (AND by default)
conditions  = [
  "agent.type == 'companion'",
  "emotion == 'joy'"
]

[effects]
change_emotion = { emotion = "gratitude", delta = "++" }
adjust_score  = { value = 5, target = "agent" }
