name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint || echo "Linting failed but continuing"

    - name: Type check
      run: npm run typecheck || echo "Type checking failed but continuing"

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ui/dist
        retention-days: 7

  analyze:
    runs-on: ubuntu-latest
    needs: test-and-build

    defaults:
      run:
        working-directory: ui

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Analyze bundle size
      run: npm run build:analyze

    - name: Upload bundle analysis
      uses: actions/upload-artifact@v4
      with:
        name: bundle-analysis
        path: ui/dist-analyze
        retention-days: 7

    - name: Run security audit
      run: npm audit --production

    - name: Check for outdated dependencies
      run: npm outdated || true
